buildpack:
  name: Blazar-Buildpack-Java

provides:
  - name: hbase-rpm

env:
  RPM_BUILD_COMMAND: "./rpm-build/build.sh"
  RPM_REPOS: "8_hs-hbase${GIT_NON_DEFAULT_BRANCH:+-develop} aarch64_8_hs-hbase${GIT_NON_DEFAULT_BRANCH:+-develop}"
  MAVEN_PHASE: package assembly:single
  MAVEN_ARGS: ""
  SET_VERSION: ""
  HBASE_VERSION: ""
  PKG_RELEASE: ""
  FULL_BUILD_VERSION: ""

before:
  - description: "Prepare build environment"
    commands:
      - $WORKSPACE/build-scripts/prepare_environment.sh

stepActivation:
  uploadRpms:
    branchRegexes: [".*"]
