##
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cxx_library(name="serde",
            exported_headers=[
                "client-serializer.h",
                "client-deserializer.h",
                "zk-deserializer.h",
            ],
            srcs=[
                "client-serializer.cc",
                "client-deserializer.cc",
                "zk-deserializer.cc",
            ],
            deps=[
                "//if:if",
                "//third-party:folly",
            ],
            tests=[
                ":client-serializer-test",
                ":client-deserializer-test",
            ],
            visibility=[
                'PUBLIC',
            ], )

cxx_test(name="client-serializer-test",
         srcs=[
             "client-serializer-test.cc",
         ],
         deps=[
             ":serde",
             "//if:if",
         ], )
cxx_test(name="client-deserializer-test",
         srcs=[
             "client-deserializer-test.cc",
         ],
         deps=[
             ":serde",
             "//if:if",
         ], )
cxx_test(name="zk-deserializer-test",
         srcs=[
             "zk-deserializer-test.cc",
         ],
         deps=[
             ":serde",
             "//if:if",
         ], )
