##
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cxx_library(name="serde",
            exported_headers=[
                "region-info.h",
                "rpc.h",
                "server-name.h",
                "table-name.h",
                "zk.h",
            ],
            srcs=[
                "rpc.cc",
                "zk.cc",
            ],
            deps=[
                "//if:if",
                "//third-party:folly",
            ],
            tests=[
                ":client-deserializer-test",
                ":client-serializer-test",
                ":server-name-test",
                ":table-name-test",
                ":zk-deserializer-test",
                ":region-info-deserializer-test",
            ],
            compiler_flags=['-Weffc++'],
            visibility=[
                'PUBLIC',
            ], )
cxx_test(name="table-name-test",
         srcs=["table-name-test.cc", ],
         deps=[":serde", ], )
cxx_test(name="server-name-test",
         srcs=["server-name-test.cc", ],
         deps=[":serde", ], )
cxx_test(name="client-serializer-test",
         srcs=["client-serializer-test.cc", ],
         deps=[":serde", ], )
cxx_test(name="client-deserializer-test",
         srcs=["client-deserializer-test.cc", ],
         deps=[":serde", ], )
cxx_test(name="zk-deserializer-test",
         srcs=["zk-deserializer-test.cc", ],
         deps=[":serde", ], )
cxx_test(name="region-info-deserializer-test",
         srcs=["region-info-deserializer-test.cc", ],
         deps=[":serde", ], )
