#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'hbase_types'

module Apache
  module Hadoop
    module Hbase
      module Thrift
      end
    end
  end
end
