// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/api.proto

package org.apache.hadoop.hbase.shaded.com.google.protobuf;

/**
 * <pre>
 * Api is a light-weight descriptor for a protocol buffer service.
 * </pre>
 *
 * Protobuf type {@code google.protobuf.Api}
 */
public  final class Api extends
    org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.protobuf.Api)
    ApiOrBuilder {
  // Use Api.newBuilder() to construct.
  private Api(org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Api() {
    name_ = "";
    methods_ = java.util.Collections.emptyList();
    options_ = java.util.Collections.emptyList();
    version_ = "";
    mixins_ = java.util.Collections.emptyList();
    syntax_ = 0;
  }

  @java.lang.Override
  public final org.apache.hadoop.hbase.shaded.com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return org.apache.hadoop.hbase.shaded.com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Api(
      org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedInputStream input,
      org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              methods_ = new java.util.ArrayList<org.apache.hadoop.hbase.shaded.com.google.protobuf.Method>();
              mutable_bitField0_ |= 0x00000002;
            }
            methods_.add(
                input.readMessage(org.apache.hadoop.hbase.shaded.com.google.protobuf.Method.parser(), extensionRegistry));
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              options_ = new java.util.ArrayList<org.apache.hadoop.hbase.shaded.com.google.protobuf.Option>();
              mutable_bitField0_ |= 0x00000004;
            }
            options_.add(
                input.readMessage(org.apache.hadoop.hbase.shaded.com.google.protobuf.Option.parser(), extensionRegistry));
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            version_ = s;
            break;
          }
          case 42: {
            org.apache.hadoop.hbase.shaded.com.google.protobuf.SourceContext.Builder subBuilder = null;
            if (sourceContext_ != null) {
              subBuilder = sourceContext_.toBuilder();
            }
            sourceContext_ = input.readMessage(org.apache.hadoop.hbase.shaded.com.google.protobuf.SourceContext.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(sourceContext_);
              sourceContext_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              mixins_ = new java.util.ArrayList<org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin>();
              mutable_bitField0_ |= 0x00000020;
            }
            mixins_.add(
                input.readMessage(org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin.parser(), extensionRegistry));
            break;
          }
          case 56: {
            int rawValue = input.readEnum();

            syntax_ = rawValue;
            break;
          }
        }
      }
    } catch (org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        methods_ = java.util.Collections.unmodifiableList(methods_);
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        options_ = java.util.Collections.unmodifiableList(options_);
      }
      if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
        mixins_ = java.util.Collections.unmodifiableList(mixins_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.apache.hadoop.hbase.shaded.com.google.protobuf.ApiProto.internal_static_google_protobuf_Api_descriptor;
  }

  protected org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.apache.hadoop.hbase.shaded.com.google.protobuf.ApiProto.internal_static_google_protobuf_Api_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.apache.hadoop.hbase.shaded.com.google.protobuf.Api.class, org.apache.hadoop.hbase.shaded.com.google.protobuf.Api.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * The fully qualified name of this api, including package name
   * followed by the api's simple name.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString bs = 
          (org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The fully qualified name of this api, including package name
   * followed by the api's simple name.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   */
  public org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString b = 
          org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METHODS_FIELD_NUMBER = 2;
  private java.util.List<org.apache.hadoop.hbase.shaded.com.google.protobuf.Method> methods_;
  /**
   * <pre>
   * The methods of this api, in unspecified order.
   * </pre>
   *
   * <code>repeated .google.protobuf.Method methods = 2;</code>
   */
  public java.util.List<org.apache.hadoop.hbase.shaded.com.google.protobuf.Method> getMethodsList() {
    return methods_;
  }
  /**
   * <pre>
   * The methods of this api, in unspecified order.
   * </pre>
   *
   * <code>repeated .google.protobuf.Method methods = 2;</code>
   */
  public java.util.List<? extends org.apache.hadoop.hbase.shaded.com.google.protobuf.MethodOrBuilder> 
      getMethodsOrBuilderList() {
    return methods_;
  }
  /**
   * <pre>
   * The methods of this api, in unspecified order.
   * </pre>
   *
   * <code>repeated .google.protobuf.Method methods = 2;</code>
   */
  public int getMethodsCount() {
    return methods_.size();
  }
  /**
   * <pre>
   * The methods of this api, in unspecified order.
   * </pre>
   *
   * <code>repeated .google.protobuf.Method methods = 2;</code>
   */
  public org.apache.hadoop.hbase.shaded.com.google.protobuf.Method getMethods(int index) {
    return methods_.get(index);
  }
  /**
   * <pre>
   * The methods of this api, in unspecified order.
   * </pre>
   *
   * <code>repeated .google.protobuf.Method methods = 2;</code>
   */
  public org.apache.hadoop.hbase.shaded.com.google.protobuf.MethodOrBuilder getMethodsOrBuilder(
      int index) {
    return methods_.get(index);
  }

  public static final int OPTIONS_FIELD_NUMBER = 3;
  private java.util.List<org.apache.hadoop.hbase.shaded.com.google.protobuf.Option> options_;
  /**
   * <pre>
   * Any metadata attached to the API.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 3;</code>
   */
  public java.util.List<org.apache.hadoop.hbase.shaded.com.google.protobuf.Option> getOptionsList() {
    return options_;
  }
  /**
   * <pre>
   * Any metadata attached to the API.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 3;</code>
   */
  public java.util.List<? extends org.apache.hadoop.hbase.shaded.com.google.protobuf.OptionOrBuilder> 
      getOptionsOrBuilderList() {
    return options_;
  }
  /**
   * <pre>
   * Any metadata attached to the API.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 3;</code>
   */
  public int getOptionsCount() {
    return options_.size();
  }
  /**
   * <pre>
   * Any metadata attached to the API.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 3;</code>
   */
  public org.apache.hadoop.hbase.shaded.com.google.protobuf.Option getOptions(int index) {
    return options_.get(index);
  }
  /**
   * <pre>
   * Any metadata attached to the API.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 3;</code>
   */
  public org.apache.hadoop.hbase.shaded.com.google.protobuf.OptionOrBuilder getOptionsOrBuilder(
      int index) {
    return options_.get(index);
  }

  public static final int VERSION_FIELD_NUMBER = 4;
  private volatile java.lang.Object version_;
  /**
   * <pre>
   * A version string for this api. If specified, must have the form
   * `major-version.minor-version`, as in `1.10`. If the minor version
   * is omitted, it defaults to zero. If the entire version field is
   * empty, the major version is derived from the package name, as
   * outlined below. If the field is not empty, the version in the
   * package name will be verified to be consistent with what is
   * provided here.
   * The versioning schema uses [semantic
   * versioning](http://semver.org) where the major version number
   * indicates a breaking change and the minor version an additive,
   * non-breaking change. Both version numbers are signals to users
   * what to expect from different versions, and should be carefully
   * chosen based on the product plan.
   * The major version is also reflected in the package name of the
   * API, which must end in `v&lt;major-version&gt;`, as in
   * `google.feature.v1`. For major versions 0 and 1, the suffix can
   * be omitted. Zero major versions must only be used for
   * experimental, none-GA apis.
   * </pre>
   *
   * <code>optional string version = 4;</code>
   */
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString bs = 
          (org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * A version string for this api. If specified, must have the form
   * `major-version.minor-version`, as in `1.10`. If the minor version
   * is omitted, it defaults to zero. If the entire version field is
   * empty, the major version is derived from the package name, as
   * outlined below. If the field is not empty, the version in the
   * package name will be verified to be consistent with what is
   * provided here.
   * The versioning schema uses [semantic
   * versioning](http://semver.org) where the major version number
   * indicates a breaking change and the minor version an additive,
   * non-breaking change. Both version numbers are signals to users
   * what to expect from different versions, and should be carefully
   * chosen based on the product plan.
   * The major version is also reflected in the package name of the
   * API, which must end in `v&lt;major-version&gt;`, as in
   * `google.feature.v1`. For major versions 0 and 1, the suffix can
   * be omitted. Zero major versions must only be used for
   * experimental, none-GA apis.
   * </pre>
   *
   * <code>optional string version = 4;</code>
   */
  public org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString b = 
          org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCE_CONTEXT_FIELD_NUMBER = 5;
  private org.apache.hadoop.hbase.shaded.com.google.protobuf.SourceContext sourceContext_;
  /**
   * <pre>
   * Source context for the protocol buffer service represented by this
   * message.
   * </pre>
   *
   * <code>optional .google.protobuf.SourceContext source_context = 5;</code>
   */
  public boolean hasSourceContext() {
    return sourceContext_ != null;
  }
  /**
   * <pre>
   * Source context for the protocol buffer service represented by this
   * message.
   * </pre>
   *
   * <code>optional .google.protobuf.SourceContext source_context = 5;</code>
   */
  public org.apache.hadoop.hbase.shaded.com.google.protobuf.SourceContext getSourceContext() {
    return sourceContext_ == null ? org.apache.hadoop.hbase.shaded.com.google.protobuf.SourceContext.getDefaultInstance() : sourceContext_;
  }
  /**
   * <pre>
   * Source context for the protocol buffer service represented by this
   * message.
   * </pre>
   *
   * <code>optional .google.protobuf.SourceContext source_context = 5;</code>
   */
  public org.apache.hadoop.hbase.shaded.com.google.protobuf.SourceContextOrBuilder getSourceContextOrBuilder() {
    return getSourceContext();
  }

  public static final int MIXINS_FIELD_NUMBER = 6;
  private java.util.List<org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin> mixins_;
  /**
   * <pre>
   * Included APIs. See [Mixin][].
   * </pre>
   *
   * <code>repeated .google.protobuf.Mixin mixins = 6;</code>
   */
  public java.util.List<org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin> getMixinsList() {
    return mixins_;
  }
  /**
   * <pre>
   * Included APIs. See [Mixin][].
   * </pre>
   *
   * <code>repeated .google.protobuf.Mixin mixins = 6;</code>
   */
  public java.util.List<? extends org.apache.hadoop.hbase.shaded.com.google.protobuf.MixinOrBuilder> 
      getMixinsOrBuilderList() {
    return mixins_;
  }
  /**
   * <pre>
   * Included APIs. See [Mixin][].
   * </pre>
   *
   * <code>repeated .google.protobuf.Mixin mixins = 6;</code>
   */
  public int getMixinsCount() {
    return mixins_.size();
  }
  /**
   * <pre>
   * Included APIs. See [Mixin][].
   * </pre>
   *
   * <code>repeated .google.protobuf.Mixin mixins = 6;</code>
   */
  public org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin getMixins(int index) {
    return mixins_.get(index);
  }
  /**
   * <pre>
   * Included APIs. See [Mixin][].
   * </pre>
   *
   * <code>repeated .google.protobuf.Mixin mixins = 6;</code>
   */
  public org.apache.hadoop.hbase.shaded.com.google.protobuf.MixinOrBuilder getMixinsOrBuilder(
      int index) {
    return mixins_.get(index);
  }

  public static final int SYNTAX_FIELD_NUMBER = 7;
  private int syntax_;
  /**
   * <pre>
   * The source syntax of the service.
   * </pre>
   *
   * <code>optional .google.protobuf.Syntax syntax = 7;</code>
   */
  public int getSyntaxValue() {
    return syntax_;
  }
  /**
   * <pre>
   * The source syntax of the service.
   * </pre>
   *
   * <code>optional .google.protobuf.Syntax syntax = 7;</code>
   */
  public org.apache.hadoop.hbase.shaded.com.google.protobuf.Syntax getSyntax() {
    org.apache.hadoop.hbase.shaded.com.google.protobuf.Syntax result = org.apache.hadoop.hbase.shaded.com.google.protobuf.Syntax.valueOf(syntax_);
    return result == null ? org.apache.hadoop.hbase.shaded.com.google.protobuf.Syntax.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    for (int i = 0; i < methods_.size(); i++) {
      output.writeMessage(2, methods_.get(i));
    }
    for (int i = 0; i < options_.size(); i++) {
      output.writeMessage(3, options_.get(i));
    }
    if (!getVersionBytes().isEmpty()) {
      org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessageV3.writeString(output, 4, version_);
    }
    if (sourceContext_ != null) {
      output.writeMessage(5, getSourceContext());
    }
    for (int i = 0; i < mixins_.size(); i++) {
      output.writeMessage(6, mixins_.get(i));
    }
    if (syntax_ != org.apache.hadoop.hbase.shaded.com.google.protobuf.Syntax.SYNTAX_PROTO2.getNumber()) {
      output.writeEnum(7, syntax_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    for (int i = 0; i < methods_.size(); i++) {
      size += org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, methods_.get(i));
    }
    for (int i = 0; i < options_.size(); i++) {
      size += org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, options_.get(i));
    }
    if (!getVersionBytes().isEmpty()) {
      size += org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessageV3.computeStringSize(4, version_);
    }
    if (sourceContext_ != null) {
      size += org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getSourceContext());
    }
    for (int i = 0; i < mixins_.size(); i++) {
      size += org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, mixins_.get(i));
    }
    if (syntax_ != org.apache.hadoop.hbase.shaded.com.google.protobuf.Syntax.SYNTAX_PROTO2.getNumber()) {
      size += org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, syntax_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.apache.hadoop.hbase.shaded.com.google.protobuf.Api)) {
      return super.equals(obj);
    }
    org.apache.hadoop.hbase.shaded.com.google.protobuf.Api other = (org.apache.hadoop.hbase.shaded.com.google.protobuf.Api) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && getMethodsList()
        .equals(other.getMethodsList());
    result = result && getOptionsList()
        .equals(other.getOptionsList());
    result = result && getVersion()
        .equals(other.getVersion());
    result = result && (hasSourceContext() == other.hasSourceContext());
    if (hasSourceContext()) {
      result = result && getSourceContext()
          .equals(other.getSourceContext());
    }
    result = result && getMixinsList()
        .equals(other.getMixinsList());
    result = result && syntax_ == other.syntax_;
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (getMethodsCount() > 0) {
      hash = (37 * hash) + METHODS_FIELD_NUMBER;
      hash = (53 * hash) + getMethodsList().hashCode();
    }
    if (getOptionsCount() > 0) {
      hash = (37 * hash) + OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOptionsList().hashCode();
    }
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    if (hasSourceContext()) {
      hash = (37 * hash) + SOURCE_CONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getSourceContext().hashCode();
    }
    if (getMixinsCount() > 0) {
      hash = (37 * hash) + MIXINS_FIELD_NUMBER;
      hash = (53 * hash) + getMixinsList().hashCode();
    }
    hash = (37 * hash) + SYNTAX_FIELD_NUMBER;
    hash = (53 * hash) + syntax_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.apache.hadoop.hbase.shaded.com.google.protobuf.Api parseFrom(
      org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString data)
      throws org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.hadoop.hbase.shaded.com.google.protobuf.Api parseFrom(
      org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString data,
      org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.hadoop.hbase.shaded.com.google.protobuf.Api parseFrom(byte[] data)
      throws org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.hadoop.hbase.shaded.com.google.protobuf.Api parseFrom(
      byte[] data,
      org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.hadoop.hbase.shaded.com.google.protobuf.Api parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.hadoop.hbase.shaded.com.google.protobuf.Api parseFrom(
      java.io.InputStream input,
      org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.hadoop.hbase.shaded.com.google.protobuf.Api parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.apache.hadoop.hbase.shaded.com.google.protobuf.Api parseDelimitedFrom(
      java.io.InputStream input,
      org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.hadoop.hbase.shaded.com.google.protobuf.Api parseFrom(
      org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.hadoop.hbase.shaded.com.google.protobuf.Api parseFrom(
      org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedInputStream input,
      org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.apache.hadoop.hbase.shaded.com.google.protobuf.Api prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Api is a light-weight descriptor for a protocol buffer service.
   * </pre>
   *
   * Protobuf type {@code google.protobuf.Api}
   */
  public static final class Builder extends
      org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.protobuf.Api)
      org.apache.hadoop.hbase.shaded.com.google.protobuf.ApiOrBuilder {
    public static final org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.hadoop.hbase.shaded.com.google.protobuf.ApiProto.internal_static_google_protobuf_Api_descriptor;
    }

    protected org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.hadoop.hbase.shaded.com.google.protobuf.ApiProto.internal_static_google_protobuf_Api_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.hadoop.hbase.shaded.com.google.protobuf.Api.class, org.apache.hadoop.hbase.shaded.com.google.protobuf.Api.Builder.class);
    }

    // Construct using org.apache.hadoop.hbase.shaded.com.google.protobuf.Api.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMethodsFieldBuilder();
        getOptionsFieldBuilder();
        getMixinsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      name_ = "";

      if (methodsBuilder_ == null) {
        methods_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        methodsBuilder_.clear();
      }
      if (optionsBuilder_ == null) {
        options_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        optionsBuilder_.clear();
      }
      version_ = "";

      if (sourceContextBuilder_ == null) {
        sourceContext_ = null;
      } else {
        sourceContext_ = null;
        sourceContextBuilder_ = null;
      }
      if (mixinsBuilder_ == null) {
        mixins_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        mixinsBuilder_.clear();
      }
      syntax_ = 0;

      return this;
    }

    public org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.apache.hadoop.hbase.shaded.com.google.protobuf.ApiProto.internal_static_google_protobuf_Api_descriptor;
    }

    public org.apache.hadoop.hbase.shaded.com.google.protobuf.Api getDefaultInstanceForType() {
      return org.apache.hadoop.hbase.shaded.com.google.protobuf.Api.getDefaultInstance();
    }

    public org.apache.hadoop.hbase.shaded.com.google.protobuf.Api build() {
      org.apache.hadoop.hbase.shaded.com.google.protobuf.Api result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.apache.hadoop.hbase.shaded.com.google.protobuf.Api buildPartial() {
      org.apache.hadoop.hbase.shaded.com.google.protobuf.Api result = new org.apache.hadoop.hbase.shaded.com.google.protobuf.Api(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.name_ = name_;
      if (methodsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          methods_ = java.util.Collections.unmodifiableList(methods_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.methods_ = methods_;
      } else {
        result.methods_ = methodsBuilder_.build();
      }
      if (optionsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          options_ = java.util.Collections.unmodifiableList(options_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.options_ = options_;
      } else {
        result.options_ = optionsBuilder_.build();
      }
      result.version_ = version_;
      if (sourceContextBuilder_ == null) {
        result.sourceContext_ = sourceContext_;
      } else {
        result.sourceContext_ = sourceContextBuilder_.build();
      }
      if (mixinsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          mixins_ = java.util.Collections.unmodifiableList(mixins_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.mixins_ = mixins_;
      } else {
        result.mixins_ = mixinsBuilder_.build();
      }
      result.syntax_ = syntax_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(org.apache.hadoop.hbase.shaded.com.google.protobuf.Message other) {
      if (other instanceof org.apache.hadoop.hbase.shaded.com.google.protobuf.Api) {
        return mergeFrom((org.apache.hadoop.hbase.shaded.com.google.protobuf.Api)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.apache.hadoop.hbase.shaded.com.google.protobuf.Api other) {
      if (other == org.apache.hadoop.hbase.shaded.com.google.protobuf.Api.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (methodsBuilder_ == null) {
        if (!other.methods_.isEmpty()) {
          if (methods_.isEmpty()) {
            methods_ = other.methods_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMethodsIsMutable();
            methods_.addAll(other.methods_);
          }
          onChanged();
        }
      } else {
        if (!other.methods_.isEmpty()) {
          if (methodsBuilder_.isEmpty()) {
            methodsBuilder_.dispose();
            methodsBuilder_ = null;
            methods_ = other.methods_;
            bitField0_ = (bitField0_ & ~0x00000002);
            methodsBuilder_ = 
              org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMethodsFieldBuilder() : null;
          } else {
            methodsBuilder_.addAllMessages(other.methods_);
          }
        }
      }
      if (optionsBuilder_ == null) {
        if (!other.options_.isEmpty()) {
          if (options_.isEmpty()) {
            options_ = other.options_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureOptionsIsMutable();
            options_.addAll(other.options_);
          }
          onChanged();
        }
      } else {
        if (!other.options_.isEmpty()) {
          if (optionsBuilder_.isEmpty()) {
            optionsBuilder_.dispose();
            optionsBuilder_ = null;
            options_ = other.options_;
            bitField0_ = (bitField0_ & ~0x00000004);
            optionsBuilder_ = 
              org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOptionsFieldBuilder() : null;
          } else {
            optionsBuilder_.addAllMessages(other.options_);
          }
        }
      }
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        onChanged();
      }
      if (other.hasSourceContext()) {
        mergeSourceContext(other.getSourceContext());
      }
      if (mixinsBuilder_ == null) {
        if (!other.mixins_.isEmpty()) {
          if (mixins_.isEmpty()) {
            mixins_ = other.mixins_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureMixinsIsMutable();
            mixins_.addAll(other.mixins_);
          }
          onChanged();
        }
      } else {
        if (!other.mixins_.isEmpty()) {
          if (mixinsBuilder_.isEmpty()) {
            mixinsBuilder_.dispose();
            mixinsBuilder_ = null;
            mixins_ = other.mixins_;
            bitField0_ = (bitField0_ & ~0x00000020);
            mixinsBuilder_ = 
              org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMixinsFieldBuilder() : null;
          } else {
            mixinsBuilder_.addAllMessages(other.mixins_);
          }
        }
      }
      if (other.syntax_ != 0) {
        setSyntaxValue(other.getSyntaxValue());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedInputStream input,
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.apache.hadoop.hbase.shaded.com.google.protobuf.Api parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.apache.hadoop.hbase.shaded.com.google.protobuf.Api) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * The fully qualified name of this api, including package name
     * followed by the api's simple name.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString bs =
            (org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The fully qualified name of this api, including package name
     * followed by the api's simple name.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString b = 
            org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The fully qualified name of this api, including package name
     * followed by the api's simple name.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The fully qualified name of this api, including package name
     * followed by the api's simple name.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The fully qualified name of this api, including package name
     * followed by the api's simple name.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public Builder setNameBytes(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.util.List<org.apache.hadoop.hbase.shaded.com.google.protobuf.Method> methods_ =
      java.util.Collections.emptyList();
    private void ensureMethodsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        methods_ = new java.util.ArrayList<org.apache.hadoop.hbase.shaded.com.google.protobuf.Method>(methods_);
        bitField0_ |= 0x00000002;
       }
    }

    private org.apache.hadoop.hbase.shaded.com.google.protobuf.RepeatedFieldBuilderV3<
        org.apache.hadoop.hbase.shaded.com.google.protobuf.Method, org.apache.hadoop.hbase.shaded.com.google.protobuf.Method.Builder, org.apache.hadoop.hbase.shaded.com.google.protobuf.MethodOrBuilder> methodsBuilder_;

    /**
     * <pre>
     * The methods of this api, in unspecified order.
     * </pre>
     *
     * <code>repeated .google.protobuf.Method methods = 2;</code>
     */
    public java.util.List<org.apache.hadoop.hbase.shaded.com.google.protobuf.Method> getMethodsList() {
      if (methodsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(methods_);
      } else {
        return methodsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The methods of this api, in unspecified order.
     * </pre>
     *
     * <code>repeated .google.protobuf.Method methods = 2;</code>
     */
    public int getMethodsCount() {
      if (methodsBuilder_ == null) {
        return methods_.size();
      } else {
        return methodsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The methods of this api, in unspecified order.
     * </pre>
     *
     * <code>repeated .google.protobuf.Method methods = 2;</code>
     */
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.Method getMethods(int index) {
      if (methodsBuilder_ == null) {
        return methods_.get(index);
      } else {
        return methodsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The methods of this api, in unspecified order.
     * </pre>
     *
     * <code>repeated .google.protobuf.Method methods = 2;</code>
     */
    public Builder setMethods(
        int index, org.apache.hadoop.hbase.shaded.com.google.protobuf.Method value) {
      if (methodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMethodsIsMutable();
        methods_.set(index, value);
        onChanged();
      } else {
        methodsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The methods of this api, in unspecified order.
     * </pre>
     *
     * <code>repeated .google.protobuf.Method methods = 2;</code>
     */
    public Builder setMethods(
        int index, org.apache.hadoop.hbase.shaded.com.google.protobuf.Method.Builder builderForValue) {
      if (methodsBuilder_ == null) {
        ensureMethodsIsMutable();
        methods_.set(index, builderForValue.build());
        onChanged();
      } else {
        methodsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The methods of this api, in unspecified order.
     * </pre>
     *
     * <code>repeated .google.protobuf.Method methods = 2;</code>
     */
    public Builder addMethods(org.apache.hadoop.hbase.shaded.com.google.protobuf.Method value) {
      if (methodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMethodsIsMutable();
        methods_.add(value);
        onChanged();
      } else {
        methodsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The methods of this api, in unspecified order.
     * </pre>
     *
     * <code>repeated .google.protobuf.Method methods = 2;</code>
     */
    public Builder addMethods(
        int index, org.apache.hadoop.hbase.shaded.com.google.protobuf.Method value) {
      if (methodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMethodsIsMutable();
        methods_.add(index, value);
        onChanged();
      } else {
        methodsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The methods of this api, in unspecified order.
     * </pre>
     *
     * <code>repeated .google.protobuf.Method methods = 2;</code>
     */
    public Builder addMethods(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.Method.Builder builderForValue) {
      if (methodsBuilder_ == null) {
        ensureMethodsIsMutable();
        methods_.add(builderForValue.build());
        onChanged();
      } else {
        methodsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The methods of this api, in unspecified order.
     * </pre>
     *
     * <code>repeated .google.protobuf.Method methods = 2;</code>
     */
    public Builder addMethods(
        int index, org.apache.hadoop.hbase.shaded.com.google.protobuf.Method.Builder builderForValue) {
      if (methodsBuilder_ == null) {
        ensureMethodsIsMutable();
        methods_.add(index, builderForValue.build());
        onChanged();
      } else {
        methodsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The methods of this api, in unspecified order.
     * </pre>
     *
     * <code>repeated .google.protobuf.Method methods = 2;</code>
     */
    public Builder addAllMethods(
        java.lang.Iterable<? extends org.apache.hadoop.hbase.shaded.com.google.protobuf.Method> values) {
      if (methodsBuilder_ == null) {
        ensureMethodsIsMutable();
        org.apache.hadoop.hbase.shaded.com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, methods_);
        onChanged();
      } else {
        methodsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The methods of this api, in unspecified order.
     * </pre>
     *
     * <code>repeated .google.protobuf.Method methods = 2;</code>
     */
    public Builder clearMethods() {
      if (methodsBuilder_ == null) {
        methods_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        methodsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The methods of this api, in unspecified order.
     * </pre>
     *
     * <code>repeated .google.protobuf.Method methods = 2;</code>
     */
    public Builder removeMethods(int index) {
      if (methodsBuilder_ == null) {
        ensureMethodsIsMutable();
        methods_.remove(index);
        onChanged();
      } else {
        methodsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The methods of this api, in unspecified order.
     * </pre>
     *
     * <code>repeated .google.protobuf.Method methods = 2;</code>
     */
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.Method.Builder getMethodsBuilder(
        int index) {
      return getMethodsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The methods of this api, in unspecified order.
     * </pre>
     *
     * <code>repeated .google.protobuf.Method methods = 2;</code>
     */
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.MethodOrBuilder getMethodsOrBuilder(
        int index) {
      if (methodsBuilder_ == null) {
        return methods_.get(index);  } else {
        return methodsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The methods of this api, in unspecified order.
     * </pre>
     *
     * <code>repeated .google.protobuf.Method methods = 2;</code>
     */
    public java.util.List<? extends org.apache.hadoop.hbase.shaded.com.google.protobuf.MethodOrBuilder> 
         getMethodsOrBuilderList() {
      if (methodsBuilder_ != null) {
        return methodsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(methods_);
      }
    }
    /**
     * <pre>
     * The methods of this api, in unspecified order.
     * </pre>
     *
     * <code>repeated .google.protobuf.Method methods = 2;</code>
     */
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.Method.Builder addMethodsBuilder() {
      return getMethodsFieldBuilder().addBuilder(
          org.apache.hadoop.hbase.shaded.com.google.protobuf.Method.getDefaultInstance());
    }
    /**
     * <pre>
     * The methods of this api, in unspecified order.
     * </pre>
     *
     * <code>repeated .google.protobuf.Method methods = 2;</code>
     */
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.Method.Builder addMethodsBuilder(
        int index) {
      return getMethodsFieldBuilder().addBuilder(
          index, org.apache.hadoop.hbase.shaded.com.google.protobuf.Method.getDefaultInstance());
    }
    /**
     * <pre>
     * The methods of this api, in unspecified order.
     * </pre>
     *
     * <code>repeated .google.protobuf.Method methods = 2;</code>
     */
    public java.util.List<org.apache.hadoop.hbase.shaded.com.google.protobuf.Method.Builder> 
         getMethodsBuilderList() {
      return getMethodsFieldBuilder().getBuilderList();
    }
    private org.apache.hadoop.hbase.shaded.com.google.protobuf.RepeatedFieldBuilderV3<
        org.apache.hadoop.hbase.shaded.com.google.protobuf.Method, org.apache.hadoop.hbase.shaded.com.google.protobuf.Method.Builder, org.apache.hadoop.hbase.shaded.com.google.protobuf.MethodOrBuilder> 
        getMethodsFieldBuilder() {
      if (methodsBuilder_ == null) {
        methodsBuilder_ = new org.apache.hadoop.hbase.shaded.com.google.protobuf.RepeatedFieldBuilderV3<
            org.apache.hadoop.hbase.shaded.com.google.protobuf.Method, org.apache.hadoop.hbase.shaded.com.google.protobuf.Method.Builder, org.apache.hadoop.hbase.shaded.com.google.protobuf.MethodOrBuilder>(
                methods_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        methods_ = null;
      }
      return methodsBuilder_;
    }

    private java.util.List<org.apache.hadoop.hbase.shaded.com.google.protobuf.Option> options_ =
      java.util.Collections.emptyList();
    private void ensureOptionsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        options_ = new java.util.ArrayList<org.apache.hadoop.hbase.shaded.com.google.protobuf.Option>(options_);
        bitField0_ |= 0x00000004;
       }
    }

    private org.apache.hadoop.hbase.shaded.com.google.protobuf.RepeatedFieldBuilderV3<
        org.apache.hadoop.hbase.shaded.com.google.protobuf.Option, org.apache.hadoop.hbase.shaded.com.google.protobuf.Option.Builder, org.apache.hadoop.hbase.shaded.com.google.protobuf.OptionOrBuilder> optionsBuilder_;

    /**
     * <pre>
     * Any metadata attached to the API.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public java.util.List<org.apache.hadoop.hbase.shaded.com.google.protobuf.Option> getOptionsList() {
      if (optionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(options_);
      } else {
        return optionsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Any metadata attached to the API.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public int getOptionsCount() {
      if (optionsBuilder_ == null) {
        return options_.size();
      } else {
        return optionsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Any metadata attached to the API.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.Option getOptions(int index) {
      if (optionsBuilder_ == null) {
        return options_.get(index);
      } else {
        return optionsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Any metadata attached to the API.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public Builder setOptions(
        int index, org.apache.hadoop.hbase.shaded.com.google.protobuf.Option value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOptionsIsMutable();
        options_.set(index, value);
        onChanged();
      } else {
        optionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Any metadata attached to the API.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public Builder setOptions(
        int index, org.apache.hadoop.hbase.shaded.com.google.protobuf.Option.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.set(index, builderForValue.build());
        onChanged();
      } else {
        optionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Any metadata attached to the API.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public Builder addOptions(org.apache.hadoop.hbase.shaded.com.google.protobuf.Option value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOptionsIsMutable();
        options_.add(value);
        onChanged();
      } else {
        optionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Any metadata attached to the API.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public Builder addOptions(
        int index, org.apache.hadoop.hbase.shaded.com.google.protobuf.Option value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOptionsIsMutable();
        options_.add(index, value);
        onChanged();
      } else {
        optionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Any metadata attached to the API.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public Builder addOptions(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.Option.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.add(builderForValue.build());
        onChanged();
      } else {
        optionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Any metadata attached to the API.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public Builder addOptions(
        int index, org.apache.hadoop.hbase.shaded.com.google.protobuf.Option.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.add(index, builderForValue.build());
        onChanged();
      } else {
        optionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Any metadata attached to the API.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public Builder addAllOptions(
        java.lang.Iterable<? extends org.apache.hadoop.hbase.shaded.com.google.protobuf.Option> values) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        org.apache.hadoop.hbase.shaded.com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, options_);
        onChanged();
      } else {
        optionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Any metadata attached to the API.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public Builder clearOptions() {
      if (optionsBuilder_ == null) {
        options_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        optionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Any metadata attached to the API.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public Builder removeOptions(int index) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.remove(index);
        onChanged();
      } else {
        optionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Any metadata attached to the API.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.Option.Builder getOptionsBuilder(
        int index) {
      return getOptionsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Any metadata attached to the API.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.OptionOrBuilder getOptionsOrBuilder(
        int index) {
      if (optionsBuilder_ == null) {
        return options_.get(index);  } else {
        return optionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Any metadata attached to the API.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public java.util.List<? extends org.apache.hadoop.hbase.shaded.com.google.protobuf.OptionOrBuilder> 
         getOptionsOrBuilderList() {
      if (optionsBuilder_ != null) {
        return optionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(options_);
      }
    }
    /**
     * <pre>
     * Any metadata attached to the API.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.Option.Builder addOptionsBuilder() {
      return getOptionsFieldBuilder().addBuilder(
          org.apache.hadoop.hbase.shaded.com.google.protobuf.Option.getDefaultInstance());
    }
    /**
     * <pre>
     * Any metadata attached to the API.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.Option.Builder addOptionsBuilder(
        int index) {
      return getOptionsFieldBuilder().addBuilder(
          index, org.apache.hadoop.hbase.shaded.com.google.protobuf.Option.getDefaultInstance());
    }
    /**
     * <pre>
     * Any metadata attached to the API.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public java.util.List<org.apache.hadoop.hbase.shaded.com.google.protobuf.Option.Builder> 
         getOptionsBuilderList() {
      return getOptionsFieldBuilder().getBuilderList();
    }
    private org.apache.hadoop.hbase.shaded.com.google.protobuf.RepeatedFieldBuilderV3<
        org.apache.hadoop.hbase.shaded.com.google.protobuf.Option, org.apache.hadoop.hbase.shaded.com.google.protobuf.Option.Builder, org.apache.hadoop.hbase.shaded.com.google.protobuf.OptionOrBuilder> 
        getOptionsFieldBuilder() {
      if (optionsBuilder_ == null) {
        optionsBuilder_ = new org.apache.hadoop.hbase.shaded.com.google.protobuf.RepeatedFieldBuilderV3<
            org.apache.hadoop.hbase.shaded.com.google.protobuf.Option, org.apache.hadoop.hbase.shaded.com.google.protobuf.Option.Builder, org.apache.hadoop.hbase.shaded.com.google.protobuf.OptionOrBuilder>(
                options_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        options_ = null;
      }
      return optionsBuilder_;
    }

    private java.lang.Object version_ = "";
    /**
     * <pre>
     * A version string for this api. If specified, must have the form
     * `major-version.minor-version`, as in `1.10`. If the minor version
     * is omitted, it defaults to zero. If the entire version field is
     * empty, the major version is derived from the package name, as
     * outlined below. If the field is not empty, the version in the
     * package name will be verified to be consistent with what is
     * provided here.
     * The versioning schema uses [semantic
     * versioning](http://semver.org) where the major version number
     * indicates a breaking change and the minor version an additive,
     * non-breaking change. Both version numbers are signals to users
     * what to expect from different versions, and should be carefully
     * chosen based on the product plan.
     * The major version is also reflected in the package name of the
     * API, which must end in `v&lt;major-version&gt;`, as in
     * `google.feature.v1`. For major versions 0 and 1, the suffix can
     * be omitted. Zero major versions must only be used for
     * experimental, none-GA apis.
     * </pre>
     *
     * <code>optional string version = 4;</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString bs =
            (org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * A version string for this api. If specified, must have the form
     * `major-version.minor-version`, as in `1.10`. If the minor version
     * is omitted, it defaults to zero. If the entire version field is
     * empty, the major version is derived from the package name, as
     * outlined below. If the field is not empty, the version in the
     * package name will be verified to be consistent with what is
     * provided here.
     * The versioning schema uses [semantic
     * versioning](http://semver.org) where the major version number
     * indicates a breaking change and the minor version an additive,
     * non-breaking change. Both version numbers are signals to users
     * what to expect from different versions, and should be carefully
     * chosen based on the product plan.
     * The major version is also reflected in the package name of the
     * API, which must end in `v&lt;major-version&gt;`, as in
     * `google.feature.v1`. For major versions 0 and 1, the suffix can
     * be omitted. Zero major versions must only be used for
     * experimental, none-GA apis.
     * </pre>
     *
     * <code>optional string version = 4;</code>
     */
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString b = 
            org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * A version string for this api. If specified, must have the form
     * `major-version.minor-version`, as in `1.10`. If the minor version
     * is omitted, it defaults to zero. If the entire version field is
     * empty, the major version is derived from the package name, as
     * outlined below. If the field is not empty, the version in the
     * package name will be verified to be consistent with what is
     * provided here.
     * The versioning schema uses [semantic
     * versioning](http://semver.org) where the major version number
     * indicates a breaking change and the minor version an additive,
     * non-breaking change. Both version numbers are signals to users
     * what to expect from different versions, and should be carefully
     * chosen based on the product plan.
     * The major version is also reflected in the package name of the
     * API, which must end in `v&lt;major-version&gt;`, as in
     * `google.feature.v1`. For major versions 0 and 1, the suffix can
     * be omitted. Zero major versions must only be used for
     * experimental, none-GA apis.
     * </pre>
     *
     * <code>optional string version = 4;</code>
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A version string for this api. If specified, must have the form
     * `major-version.minor-version`, as in `1.10`. If the minor version
     * is omitted, it defaults to zero. If the entire version field is
     * empty, the major version is derived from the package name, as
     * outlined below. If the field is not empty, the version in the
     * package name will be verified to be consistent with what is
     * provided here.
     * The versioning schema uses [semantic
     * versioning](http://semver.org) where the major version number
     * indicates a breaking change and the minor version an additive,
     * non-breaking change. Both version numbers are signals to users
     * what to expect from different versions, and should be carefully
     * chosen based on the product plan.
     * The major version is also reflected in the package name of the
     * API, which must end in `v&lt;major-version&gt;`, as in
     * `google.feature.v1`. For major versions 0 and 1, the suffix can
     * be omitted. Zero major versions must only be used for
     * experimental, none-GA apis.
     * </pre>
     *
     * <code>optional string version = 4;</code>
     */
    public Builder clearVersion() {
      
      version_ = getDefaultInstance().getVersion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A version string for this api. If specified, must have the form
     * `major-version.minor-version`, as in `1.10`. If the minor version
     * is omitted, it defaults to zero. If the entire version field is
     * empty, the major version is derived from the package name, as
     * outlined below. If the field is not empty, the version in the
     * package name will be verified to be consistent with what is
     * provided here.
     * The versioning schema uses [semantic
     * versioning](http://semver.org) where the major version number
     * indicates a breaking change and the minor version an additive,
     * non-breaking change. Both version numbers are signals to users
     * what to expect from different versions, and should be carefully
     * chosen based on the product plan.
     * The major version is also reflected in the package name of the
     * API, which must end in `v&lt;major-version&gt;`, as in
     * `google.feature.v1`. For major versions 0 and 1, the suffix can
     * be omitted. Zero major versions must only be used for
     * experimental, none-GA apis.
     * </pre>
     *
     * <code>optional string version = 4;</code>
     */
    public Builder setVersionBytes(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      version_ = value;
      onChanged();
      return this;
    }

    private org.apache.hadoop.hbase.shaded.com.google.protobuf.SourceContext sourceContext_ = null;
    private org.apache.hadoop.hbase.shaded.com.google.protobuf.SingleFieldBuilderV3<
        org.apache.hadoop.hbase.shaded.com.google.protobuf.SourceContext, org.apache.hadoop.hbase.shaded.com.google.protobuf.SourceContext.Builder, org.apache.hadoop.hbase.shaded.com.google.protobuf.SourceContextOrBuilder> sourceContextBuilder_;
    /**
     * <pre>
     * Source context for the protocol buffer service represented by this
     * message.
     * </pre>
     *
     * <code>optional .google.protobuf.SourceContext source_context = 5;</code>
     */
    public boolean hasSourceContext() {
      return sourceContextBuilder_ != null || sourceContext_ != null;
    }
    /**
     * <pre>
     * Source context for the protocol buffer service represented by this
     * message.
     * </pre>
     *
     * <code>optional .google.protobuf.SourceContext source_context = 5;</code>
     */
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.SourceContext getSourceContext() {
      if (sourceContextBuilder_ == null) {
        return sourceContext_ == null ? org.apache.hadoop.hbase.shaded.com.google.protobuf.SourceContext.getDefaultInstance() : sourceContext_;
      } else {
        return sourceContextBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Source context for the protocol buffer service represented by this
     * message.
     * </pre>
     *
     * <code>optional .google.protobuf.SourceContext source_context = 5;</code>
     */
    public Builder setSourceContext(org.apache.hadoop.hbase.shaded.com.google.protobuf.SourceContext value) {
      if (sourceContextBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sourceContext_ = value;
        onChanged();
      } else {
        sourceContextBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Source context for the protocol buffer service represented by this
     * message.
     * </pre>
     *
     * <code>optional .google.protobuf.SourceContext source_context = 5;</code>
     */
    public Builder setSourceContext(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.SourceContext.Builder builderForValue) {
      if (sourceContextBuilder_ == null) {
        sourceContext_ = builderForValue.build();
        onChanged();
      } else {
        sourceContextBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Source context for the protocol buffer service represented by this
     * message.
     * </pre>
     *
     * <code>optional .google.protobuf.SourceContext source_context = 5;</code>
     */
    public Builder mergeSourceContext(org.apache.hadoop.hbase.shaded.com.google.protobuf.SourceContext value) {
      if (sourceContextBuilder_ == null) {
        if (sourceContext_ != null) {
          sourceContext_ =
            org.apache.hadoop.hbase.shaded.com.google.protobuf.SourceContext.newBuilder(sourceContext_).mergeFrom(value).buildPartial();
        } else {
          sourceContext_ = value;
        }
        onChanged();
      } else {
        sourceContextBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Source context for the protocol buffer service represented by this
     * message.
     * </pre>
     *
     * <code>optional .google.protobuf.SourceContext source_context = 5;</code>
     */
    public Builder clearSourceContext() {
      if (sourceContextBuilder_ == null) {
        sourceContext_ = null;
        onChanged();
      } else {
        sourceContext_ = null;
        sourceContextBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Source context for the protocol buffer service represented by this
     * message.
     * </pre>
     *
     * <code>optional .google.protobuf.SourceContext source_context = 5;</code>
     */
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.SourceContext.Builder getSourceContextBuilder() {
      
      onChanged();
      return getSourceContextFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Source context for the protocol buffer service represented by this
     * message.
     * </pre>
     *
     * <code>optional .google.protobuf.SourceContext source_context = 5;</code>
     */
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.SourceContextOrBuilder getSourceContextOrBuilder() {
      if (sourceContextBuilder_ != null) {
        return sourceContextBuilder_.getMessageOrBuilder();
      } else {
        return sourceContext_ == null ?
            org.apache.hadoop.hbase.shaded.com.google.protobuf.SourceContext.getDefaultInstance() : sourceContext_;
      }
    }
    /**
     * <pre>
     * Source context for the protocol buffer service represented by this
     * message.
     * </pre>
     *
     * <code>optional .google.protobuf.SourceContext source_context = 5;</code>
     */
    private org.apache.hadoop.hbase.shaded.com.google.protobuf.SingleFieldBuilderV3<
        org.apache.hadoop.hbase.shaded.com.google.protobuf.SourceContext, org.apache.hadoop.hbase.shaded.com.google.protobuf.SourceContext.Builder, org.apache.hadoop.hbase.shaded.com.google.protobuf.SourceContextOrBuilder> 
        getSourceContextFieldBuilder() {
      if (sourceContextBuilder_ == null) {
        sourceContextBuilder_ = new org.apache.hadoop.hbase.shaded.com.google.protobuf.SingleFieldBuilderV3<
            org.apache.hadoop.hbase.shaded.com.google.protobuf.SourceContext, org.apache.hadoop.hbase.shaded.com.google.protobuf.SourceContext.Builder, org.apache.hadoop.hbase.shaded.com.google.protobuf.SourceContextOrBuilder>(
                getSourceContext(),
                getParentForChildren(),
                isClean());
        sourceContext_ = null;
      }
      return sourceContextBuilder_;
    }

    private java.util.List<org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin> mixins_ =
      java.util.Collections.emptyList();
    private void ensureMixinsIsMutable() {
      if (!((bitField0_ & 0x00000020) == 0x00000020)) {
        mixins_ = new java.util.ArrayList<org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin>(mixins_);
        bitField0_ |= 0x00000020;
       }
    }

    private org.apache.hadoop.hbase.shaded.com.google.protobuf.RepeatedFieldBuilderV3<
        org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin, org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin.Builder, org.apache.hadoop.hbase.shaded.com.google.protobuf.MixinOrBuilder> mixinsBuilder_;

    /**
     * <pre>
     * Included APIs. See [Mixin][].
     * </pre>
     *
     * <code>repeated .google.protobuf.Mixin mixins = 6;</code>
     */
    public java.util.List<org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin> getMixinsList() {
      if (mixinsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(mixins_);
      } else {
        return mixinsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Included APIs. See [Mixin][].
     * </pre>
     *
     * <code>repeated .google.protobuf.Mixin mixins = 6;</code>
     */
    public int getMixinsCount() {
      if (mixinsBuilder_ == null) {
        return mixins_.size();
      } else {
        return mixinsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Included APIs. See [Mixin][].
     * </pre>
     *
     * <code>repeated .google.protobuf.Mixin mixins = 6;</code>
     */
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin getMixins(int index) {
      if (mixinsBuilder_ == null) {
        return mixins_.get(index);
      } else {
        return mixinsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Included APIs. See [Mixin][].
     * </pre>
     *
     * <code>repeated .google.protobuf.Mixin mixins = 6;</code>
     */
    public Builder setMixins(
        int index, org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin value) {
      if (mixinsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMixinsIsMutable();
        mixins_.set(index, value);
        onChanged();
      } else {
        mixinsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Included APIs. See [Mixin][].
     * </pre>
     *
     * <code>repeated .google.protobuf.Mixin mixins = 6;</code>
     */
    public Builder setMixins(
        int index, org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin.Builder builderForValue) {
      if (mixinsBuilder_ == null) {
        ensureMixinsIsMutable();
        mixins_.set(index, builderForValue.build());
        onChanged();
      } else {
        mixinsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Included APIs. See [Mixin][].
     * </pre>
     *
     * <code>repeated .google.protobuf.Mixin mixins = 6;</code>
     */
    public Builder addMixins(org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin value) {
      if (mixinsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMixinsIsMutable();
        mixins_.add(value);
        onChanged();
      } else {
        mixinsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Included APIs. See [Mixin][].
     * </pre>
     *
     * <code>repeated .google.protobuf.Mixin mixins = 6;</code>
     */
    public Builder addMixins(
        int index, org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin value) {
      if (mixinsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMixinsIsMutable();
        mixins_.add(index, value);
        onChanged();
      } else {
        mixinsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Included APIs. See [Mixin][].
     * </pre>
     *
     * <code>repeated .google.protobuf.Mixin mixins = 6;</code>
     */
    public Builder addMixins(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin.Builder builderForValue) {
      if (mixinsBuilder_ == null) {
        ensureMixinsIsMutable();
        mixins_.add(builderForValue.build());
        onChanged();
      } else {
        mixinsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Included APIs. See [Mixin][].
     * </pre>
     *
     * <code>repeated .google.protobuf.Mixin mixins = 6;</code>
     */
    public Builder addMixins(
        int index, org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin.Builder builderForValue) {
      if (mixinsBuilder_ == null) {
        ensureMixinsIsMutable();
        mixins_.add(index, builderForValue.build());
        onChanged();
      } else {
        mixinsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Included APIs. See [Mixin][].
     * </pre>
     *
     * <code>repeated .google.protobuf.Mixin mixins = 6;</code>
     */
    public Builder addAllMixins(
        java.lang.Iterable<? extends org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin> values) {
      if (mixinsBuilder_ == null) {
        ensureMixinsIsMutable();
        org.apache.hadoop.hbase.shaded.com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, mixins_);
        onChanged();
      } else {
        mixinsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Included APIs. See [Mixin][].
     * </pre>
     *
     * <code>repeated .google.protobuf.Mixin mixins = 6;</code>
     */
    public Builder clearMixins() {
      if (mixinsBuilder_ == null) {
        mixins_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        mixinsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Included APIs. See [Mixin][].
     * </pre>
     *
     * <code>repeated .google.protobuf.Mixin mixins = 6;</code>
     */
    public Builder removeMixins(int index) {
      if (mixinsBuilder_ == null) {
        ensureMixinsIsMutable();
        mixins_.remove(index);
        onChanged();
      } else {
        mixinsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Included APIs. See [Mixin][].
     * </pre>
     *
     * <code>repeated .google.protobuf.Mixin mixins = 6;</code>
     */
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin.Builder getMixinsBuilder(
        int index) {
      return getMixinsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Included APIs. See [Mixin][].
     * </pre>
     *
     * <code>repeated .google.protobuf.Mixin mixins = 6;</code>
     */
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.MixinOrBuilder getMixinsOrBuilder(
        int index) {
      if (mixinsBuilder_ == null) {
        return mixins_.get(index);  } else {
        return mixinsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Included APIs. See [Mixin][].
     * </pre>
     *
     * <code>repeated .google.protobuf.Mixin mixins = 6;</code>
     */
    public java.util.List<? extends org.apache.hadoop.hbase.shaded.com.google.protobuf.MixinOrBuilder> 
         getMixinsOrBuilderList() {
      if (mixinsBuilder_ != null) {
        return mixinsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(mixins_);
      }
    }
    /**
     * <pre>
     * Included APIs. See [Mixin][].
     * </pre>
     *
     * <code>repeated .google.protobuf.Mixin mixins = 6;</code>
     */
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin.Builder addMixinsBuilder() {
      return getMixinsFieldBuilder().addBuilder(
          org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin.getDefaultInstance());
    }
    /**
     * <pre>
     * Included APIs. See [Mixin][].
     * </pre>
     *
     * <code>repeated .google.protobuf.Mixin mixins = 6;</code>
     */
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin.Builder addMixinsBuilder(
        int index) {
      return getMixinsFieldBuilder().addBuilder(
          index, org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin.getDefaultInstance());
    }
    /**
     * <pre>
     * Included APIs. See [Mixin][].
     * </pre>
     *
     * <code>repeated .google.protobuf.Mixin mixins = 6;</code>
     */
    public java.util.List<org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin.Builder> 
         getMixinsBuilderList() {
      return getMixinsFieldBuilder().getBuilderList();
    }
    private org.apache.hadoop.hbase.shaded.com.google.protobuf.RepeatedFieldBuilderV3<
        org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin, org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin.Builder, org.apache.hadoop.hbase.shaded.com.google.protobuf.MixinOrBuilder> 
        getMixinsFieldBuilder() {
      if (mixinsBuilder_ == null) {
        mixinsBuilder_ = new org.apache.hadoop.hbase.shaded.com.google.protobuf.RepeatedFieldBuilderV3<
            org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin, org.apache.hadoop.hbase.shaded.com.google.protobuf.Mixin.Builder, org.apache.hadoop.hbase.shaded.com.google.protobuf.MixinOrBuilder>(
                mixins_,
                ((bitField0_ & 0x00000020) == 0x00000020),
                getParentForChildren(),
                isClean());
        mixins_ = null;
      }
      return mixinsBuilder_;
    }

    private int syntax_ = 0;
    /**
     * <pre>
     * The source syntax of the service.
     * </pre>
     *
     * <code>optional .google.protobuf.Syntax syntax = 7;</code>
     */
    public int getSyntaxValue() {
      return syntax_;
    }
    /**
     * <pre>
     * The source syntax of the service.
     * </pre>
     *
     * <code>optional .google.protobuf.Syntax syntax = 7;</code>
     */
    public Builder setSyntaxValue(int value) {
      syntax_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The source syntax of the service.
     * </pre>
     *
     * <code>optional .google.protobuf.Syntax syntax = 7;</code>
     */
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.Syntax getSyntax() {
      org.apache.hadoop.hbase.shaded.com.google.protobuf.Syntax result = org.apache.hadoop.hbase.shaded.com.google.protobuf.Syntax.valueOf(syntax_);
      return result == null ? org.apache.hadoop.hbase.shaded.com.google.protobuf.Syntax.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * The source syntax of the service.
     * </pre>
     *
     * <code>optional .google.protobuf.Syntax syntax = 7;</code>
     */
    public Builder setSyntax(org.apache.hadoop.hbase.shaded.com.google.protobuf.Syntax value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      syntax_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The source syntax of the service.
     * </pre>
     *
     * <code>optional .google.protobuf.Syntax syntax = 7;</code>
     */
    public Builder clearSyntax() {
      
      syntax_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final org.apache.hadoop.hbase.shaded.com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final org.apache.hadoop.hbase.shaded.com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:google.protobuf.Api)
  }

  // @@protoc_insertion_point(class_scope:google.protobuf.Api)
  private static final org.apache.hadoop.hbase.shaded.com.google.protobuf.Api DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.apache.hadoop.hbase.shaded.com.google.protobuf.Api();
  }

  public static org.apache.hadoop.hbase.shaded.com.google.protobuf.Api getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final org.apache.hadoop.hbase.shaded.com.google.protobuf.Parser<Api>
      PARSER = new org.apache.hadoop.hbase.shaded.com.google.protobuf.AbstractParser<Api>() {
    public Api parsePartialFrom(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedInputStream input,
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException {
        return new Api(input, extensionRegistry);
    }
  };

  public static org.apache.hadoop.hbase.shaded.com.google.protobuf.Parser<Api> parser() {
    return PARSER;
  }

  @java.lang.Override
  public org.apache.hadoop.hbase.shaded.com.google.protobuf.Parser<Api> getParserForType() {
    return PARSER;
  }

  public org.apache.hadoop.hbase.shaded.com.google.protobuf.Api getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

