// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/wrappers.proto

package org.apache.hadoop.hbase.shaded.com.google.protobuf;

public interface BytesValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.BytesValue)
    org.apache.hadoop.hbase.shaded.com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The bytes value.
   * </pre>
   *
   * <code>optional bytes value = 1;</code>
   */
  org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString getValue();
}
