// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/empty.proto

package org.apache.hadoop.hbase.shaded.com.google.protobuf;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.Empty)
    org.apache.hadoop.hbase.shaded.com.google.protobuf.MessageOrBuilder {
}
