// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/wrappers.proto

package org.apache.hadoop.hbase.shaded.com.google.protobuf;

public interface FloatValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.FloatValue)
    org.apache.hadoop.hbase.shaded.com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The float value.
   * </pre>
   *
   * <code>optional float value = 1;</code>
   */
  float getValue();
}
