// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/wrappers.proto

package org.apache.hadoop.hbase.shaded.com.google.protobuf;

public interface StringValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.StringValue)
    org.apache.hadoop.hbase.shaded.com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The string value.
   * </pre>
   *
   * <code>optional string value = 1;</code>
   */
  java.lang.String getValue();
  /**
   * <pre>
   * The string value.
   * </pre>
   *
   * <code>optional string value = 1;</code>
   */
  org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString
      getValueBytes();
}
