##
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is the library dealing with a single connection
# to a single server.
cxx_library(
    name="connection",
    exported_headers=[
        "client-dispatcher.h",
        "client-handler.h",
        "sasl-handler.h",
        "connection-factory.h",
        "connection-pool.h",
        "connection-id.h",
        "pipeline.h",
        "request.h",
        "rpc-connection.h",
        "response.h",
        "service.h",
        "rpc-client.h",
        "sasl-util.h",
        "rpc-test-server.h",
        "rpc-test-server-handler.h",
        "rpc-fault-injector.h",
        "rpc-fault-injector-inl.h",
    ],
    srcs=[
        "client-dispatcher.cc",
        "client-handler.cc",
        "connection-factory.cc",
        "connection-pool.cc",
        "pipeline.cc",
        "request.cc",
        "rpc-client.cc",
        "sasl-handler.cc",
        "sasl-util.cc",
        "rpc-test-server.cc",
        "rpc-test-server-handler.cc",
        "rpc-fault-injector.cc",
    ],
    deps=[
        "//if:if",
        "//utils:utils",
        "//serde:serde",
        "//security:security",
        "//third-party:folly",
        "//third-party:wangle",
        "//exceptions:exceptions",
    ],
    compiler_flags=['-Weffc++'],
    linker_flags=['-L/usr/local/lib', '-lsasl2', '-lkrb5'],
    exported_linker_flags=['-L/usr/local/lib', '-lsasl2', '-lkrb5'],
    visibility=[
        '//core/...',
    ],)
cxx_test(
    name="connection-pool-test",
    srcs=[
        "connection-pool-test.cc",
    ],
    deps=[
        ":connection",
    ],)
cxx_test(
    name="rpc-test",
    srcs=[
        "rpc-test.cc",
    ],
    deps=[
        ":connection",
    ],
    run_test_separately=True,)
