##
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is the library dealing with a single connection
# to a single server.
cxx_library(name="connection",
            exported_headers=[
                "client-dispatcher.h",
                "client-handler.h",
                "connection-factory.h",
                "pipeline.h",
                "request.h",
                "response.h",
                "service.h",
            ],
            srcs=[
                "client-dispatcher.cc",
                "client-handler.cc",
                "connection-factory.cc",
                "pipeline.cc",
                "request.cc",
            ],
            deps=[
                "//if:if",
                "//utils:utils",
                "//serde:serde",
                "//third-party:folly",
                "//third-party:wangle",
            ],
            visibility=['//core/...', ], )
