##
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cxx_library(
    name="utils",
    exported_headers=[
        "bytes-util.h",
        "connection-util.h",
        "concurrent-map.h",
        "optional.h",
        "sys-util.h",
        "time-util.h",
        "user-util.h",
        "version.h",
    ],
    srcs=["bytes-util.cc", "connection-util.cc", "user-util.cc"],
    deps=[
        '//third-party:folly',
    ],
    tests=[":user-util-test"],
    linker_flags=['-L/usr/local/lib', '-lkrb5'],
    exported_linker_flags=['-L/usr/local/lib', '-lkrb5'],
    visibility=[
        'PUBLIC',
    ],
    compiler_flags=['-Weffc++'],)
cxx_test(
    name="bytes-util-test",
    srcs=[
        "bytes-util-test.cc",
    ],
    deps=[
        ":utils",
    ],)
cxx_test(
    name="concurrent-map-test",
    srcs=[
        "concurrent-map-test.cc",
    ],
    deps=[
        ":utils",
    ],)
cxx_test(
    name="user-util-test",
    srcs=[
        "user-util-test.cc",
    ],
    deps=[
        ":utils",
    ],)