##
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is the main library.
cxx_library(
    name="client",
    header_namespace="hbase/client",
    exported_headers=[
        "async-client-scanner.h",
        "async-connection.h",
        "async-region-locator.h",
        "async-rpc-retrying-caller-factory.h",
        "async-rpc-retrying-caller.h",
        "async-table-result-scanner.h",
        "client.h",
        "cell.h",
        "filter.h",
        "query.h",
        "keyvalue-codec.h",
        "region-location.h",
        "location-cache.h",
        "connection-configuration.h",
        # TODO: move this out of exported
        # Once meta lookup works
        "meta-utils.h",
        "get.h",
        "increment.h",
        "mutation.h",
        "put.h",
        "delete.h",
        "scan.h",
        "append.h",
        "result.h",
        "result-scanner.h",
        "request-converter.h",
        "response-converter.h",
        "table.h",
        "async-scan-rpc-retrying-caller.h",
        "raw-async-table.h",
        "raw-scan-result-consumer.h",
        "scan-result-cache.h",
        "hbase-rpc-controller.h",
        "time-range.h",
        "zk-util.h",
        "action.h",
        "multi-response.h",
        "region-request.h",
        "region-result.h",
        "row.h",
        "server-request.h",
        "async-batch-rpc-retrying-caller.h",
    ],
    deps=[
        "//include/hbase/exceptions:exceptions",
        "//include/hbase/utils:utils",
        "//include/hbase/connection:connection",
        "//include/hbase/client:conf",
        "//src/hbase/if:if",
        "//include/hbase/serde:serde",
        "//third-party:folly",
        "//third-party:wangle",
        "//third-party:zookeeper_mt",
    ],
    compiler_flags=['-Weffc++', '-ggdb'],
    visibility=[
        'PUBLIC',
    ],)
cxx_library(
    name="conf",
    header_namespace="hbase/client",
    exported_headers=[
        "configuration.h",
        "hbase-configuration-loader.h",
    ],
    deps=["//src/hbase/utils:utils", "//third-party:folly"],
    compiler_flags=['-Weffc++', '-ggdb'],
    visibility=[
        'PUBLIC',
    ],)
