##
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cxx_library(name="core",
            headers=[
                "admin.h",
                "client.h",
                "connection.h",
                "connection_attr.h",
                "delete.h",
                "get.h",
                "hbase_macros.h",
                "mutation.h",
                "put.h",
                "scanner.h",
                "location-cache.h",
            ],
            srcs=[
                "admin.cc",
                "client.cc",
                "connection.cc",
                "get.cc",
                "mutation.cc",
                "put.cc",
                "delete.cc",
                "scanner.cc",
                "location-cache.cc",
            ],
            deps=[
                "//if:if",
                "//third-party:zookeeper_mt",
                "//third-party:folly",
                "//third-party:wangle",
            ],
            visibility=[
                'PUBLIC',
            ], )

cxx_test(name="simple-test",
         headers=[
             "test_env.h",
         ],
         srcs=[
             "native-client-test-env.cc",
             "simple-native-client-test.cc",
         ],
         deps=[
             ":core",
         ],
         run_test_separately=True, )
cxx_test(name="location-cache-test",
         headers=[
             "test_env.h",
         ],
         srcs=[
             "native-client-test-env.cc",
             "location-cache-test.cc",
         ],
         deps=[
             ":core",
         ],
         run_test_separately=True, )
