#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

forge "https://forgeapi.puppetlabs.com"

mod 'puppet-packages',
  :git => "https://github.com/greenaar/puppet-packages.git",
  :ref => '8d6b8a85eea931e4cd045884d5786c1c1ff0df4c'
mod 'puppetlabs-docker', '3.10.1'
mod 'puppetlabs-stdlib', '5.2.0'
mod 'puppetlabs-vcsrepo', '3.1.0'
mod 'saz-ssh', '6.2.0'
