/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.hadoop.hbase.io.crypto;

import java.io.IOException;
import java.util.Base64;

import org.apache.hadoop.conf.Configuration;
import org.apache.yetus.audience.InterfaceAudience;

/**
 * Interface for key providers of managed keys. Defines methods for generating and managing
 * managed keys, as well as handling key storage and retrieval.
 *
 * The interface extends the basic {@link KeyProvider} interface with additional
 * methods for working with managed keys.
 */
@InterfaceAudience.Public
public interface ManagedKeyProvider extends KeyProvider {
  /**
   * Initialize the provider with the given configuration.
   *
   * @param conf Hadoop configuration
   */
  void initConfig(Configuration conf);

  /**
   * Retrieve the system key using the given system identifier.
   *
   * @param systemId system identifier
   * @return ManagedKeyData for the system key and is guaranteed to be not {@code null}
   * @throws IOException if an error occurs while retrieving the key
   */
  ManagedKeyData getSystemKey(byte[] systemId) throws IOException;

  /**
   * Retrieve a managed key for the specified prefix.
   *
   * @param key_cust     The key custodian.
   * @param key_namespace Key namespace
   * @return ManagedKeyData for the system key and is expected to be not {@code null}
   * @throws IOException if an error occurs while retrieving the key
   */
  ManagedKeyData getManagedKey(byte[] key_cust, String key_namespace) throws IOException;

  /**
   * Retrieve a key identified by the key metadata. The key metadata is typically generated by the
   * same key provider via the {@link #getSystemKey(byte[])} or
   * {@link #getManagedKey(byte[], String)} methods. If key couldn't be retrieved using metadata and
   * the wrappedKey is provided, the implementation may try to decrypt it as a fallback operation.
   *
   * @param keyMetaData Key metadata, must not be {@code null}.
   * @param wrappedKey The DEK key material encrypted with the corresponding KEK, if available.
   * @return ManagedKeyData for the key represented by the metadata and is expected to be not
   *         {@code null}
   * @throws IOException if an error occurs while generating the key
   */
  ManagedKeyData unwrapKey(String keyMetaData, byte[] wrappedKey) throws IOException;

  /**
   * Decode the given key custodian which is encoded as Base64 string.
   * @param encodedKeyCust The encoded key custodian
   * @return the decoded key custodian
   * @throws IOException
   */
  static byte[] decodeToBytes(String encodedKeyCust) throws IOException {
    byte[] key_cust;
    try {
      key_cust = Base64.getDecoder().decode(encodedKeyCust);
    }
    catch (IllegalArgumentException e) {
      throw new IOException("Failed to decode specified key custodian as Base64 string: "
          + encodedKeyCust, e);
    }
    return key_cust;
  }

  /**
   * Encode the given key custodian as Base64 string.
   * @param key_cust The key custodian
   * @return the encoded key custodian as Base64 string
   */
  static String encodeToStr(byte[] key_cust) {
    return Base64.getEncoder().encodeToString(key_cust);
  }

}
