/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.hadoop.hbase.io.crypto;

import org.apache.hadoop.conf.Configuration;
import org.apache.yetus.audience.InterfaceAudience;
import java.io.IOException;

/**
 * Interface for PBE-based key providers. Defines methods for generating and managing
 * PBE-derived keys, as well as handling key storage and retrieval.
 *
 * The interface extends the basic {@link KeyProvider} interface with additional
 * methods for working with PBE keys.
 */
@InterfaceAudience.Public
public interface PBEKeyProvider extends KeyProvider {
  /**
   * Initialize the provider with the given configuration.
   *
   * @param conf Hadoop configuration
   */
  void initConfig(Configuration conf);

  /**
   * Retrieve the cluster key using the given cluster identifier.
   *
   * @param clusterId Cluster identifier
   * @return PBEKeyData for the cluster key and is guaranteed to be not {@code null}
   * @throws IOException if an error occurs while retrieving the key
   */
  PBEKeyData getClusterKey(byte[] clusterId) throws IOException;

  /**
   * Retrieve a PBE-based key for the specified prefix.
   *
   * @param pbe_prefix    Key prefix
   * @param key_namespace Key namespace
   * @return PBEKeyData for the cluster key and is expected to be not {@code null}
   * @throws IOException if an error occurs while retrieving the key
   */
  PBEKeyData getPBEKey(byte[] pbe_prefix, String key_namespace) throws IOException;

  /**
   * Retrieve a key identified by the key metadata. The key metadata is typically generated by the
   * same key provider via the {@link #getClusterKey(byte[])} or {@link #getPBEKey(byte[], String)}
   * methods.
   *
   * @param keyMetaData Key metadata
   * @return PBEKeyData for the key represented by the metadata and is expected to be not
   *   {@code null}
   * @throws IOException if an error occurs while generating the key
   */
  PBEKeyData unwrapKey(String keyMetaData) throws IOException;
}
