#!/bin/sh

# This file is used to generate the annotation of package info that
# records the user, url, revision and timestamp.

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

unset LANG
unset LC_CTYPE
version=$1
outputDirectory=$2
user=`whoami`
date=`date`
cwd=`pwd`
if [ -d .svn ]; then
  svn_revision=`svn info | sed -n -e 's/Last Changed Rev: \(.*\)/\1/p'`
  url=`svn info | sed -n -e 's/URL: \(.*\)/\1/p'`
	branch=`echo $url | cut -f7 -d\/`
  revision=$branch@$svn_revision
elif [ -d .git ]; then
  revision=`git log -1 --pretty=format:"%H"`
  hostname=`hostname`
  url="git://${hostname}${cwd}"
else
	which git  > /dev/null
	if [ $? == 0 ]; then 
		revision=`git log -1 | grep "git-svn-id:" | tail -1| awk '{print $2}' | cut -f7 -d\/`

		hostname=`hostname`
		if [ "$revision" == "" ]; then
			git_revision=`git log -1 --pretty=format:"%H"`
			git_branch=`git branch 2> /dev/null | grep -e '\* ' | sed 's/^..\(.*\)/\1/'`
			revision="LocalCommit: $git_branch@$git_revision"
		fi
		url="git://${hostname}${cwd}"
	else
		revision="Unknown"
		url="file://$cwd"
	fi
fi
mkdir -p "$outputDirectory/org/apache/hadoop/hbase"
cat >"$outputDirectory/org/apache/hadoop/hbase/package-info.java" <<EOF
/*
 * Generated by src/saveVersion.sh
 */
@VersionAnnotation(version="$version", revision="$revision",
                         user="$user", date="$date", url="$url")
package org.apache.hadoop.hbase;
EOF
