package org.apache.hadoop.hbase.consensus.raft.transitions;

import org.apache.hadoop.hbase.consensus.fsm.TransitionType;

public enum RaftTransitionType implements TransitionType {
  NONE,
  UNCONDITIONAL,

  ON_START,
  ON_PROGRESS_TIMEOUT,

  ON_VOTE_REQUEST,
  ON_VOTE_RESPONSE,

  ON_VOTE_SUCCEEDED,
  ON_VOTE_FAILED,
  ON_VOTE_NOT_COMPLETED,

  ON_APPEND_REQUEST,
  ON_APPEND_RESPONSE,

  ON_APPEND_SUCCEEDED,
  ON_NEED_STEPDOWN,
  ON_APPEND_RETRY,
  ON_APPEND_NOT_COMPLETED,
  ON_APPEND_TIMEOUT,

  ON_REPLICATED_ENTRIES,

  IS_LEADER,
  IS_CANDIDATE,
  IS_FOLLOWER,

  ON_QUORUM_MEMBERSHIP_CHANGE_REQUEST,
  IS_QUORUM_MEMBERSHIP_CHANGE_IN_PROGRESS,
  QUORUM_MEMBERSHIP_CHANGE_NOT_IN_PROGRESS,

  ON_TRANSACTION_LOG_NOT_ACCESSIBLE,

  ON_RESEED_REQUEST,

  ON_HALT,
  MAX
}
